In [1]:
import torch

In [2]:
iui = torch.load("iui_attn")
ibi = torch.load("ibi_attn")

In [3]:
src = iui[0][0][0]
dst = iui[0][0][1]
val = iui[0][1]

In [4]:
num = 2904 # and 7

In [5]:
src[(dst==num).nonzero()].view(-1), dst[(dst==num).nonzero()].view(-1)

(tensor([   7, 1700]), tensor([2904, 2904]))

In [51]:
x = 7
src[(dst==x).nonzero()].view(-1), dst[(dst==x).nonzero()].view(-1)

(tensor([ 671, 1700, 2904]), tensor([7, 7, 7]))

7 Converse Unisex Chuck Taylor All Star Hi Top Black Monochrome Sneaker

671 Black Ladies Cotton Leggings Full Length

1700 Skechers Kids 80573L Lite Dreamz - Brite Sport Athletic Sneaker (Little Kid)

2904 DC Kids Cole Pro Skate Shoe

In [53]:
val[(dst==7).nonzero()]

tensor([[[0.3333, 0.3341, 0.3338]],

        [[0.3327, 0.3323, 0.3334]],

        [[0.3340, 0.3336, 0.3328]]], grad_fn=<IndexBackward0>)

In [54]:
val[(dst==671).nonzero()]

tensor([[[1., 1., 1.]]], grad_fn=<IndexBackward0>)

In [55]:
val[(dst==1700).nonzero()]

tensor([[[0.4987, 0.4992, 0.5004]],

        [[0.5013, 0.5008, 0.4996]]], grad_fn=<IndexBackward0>)

In [56]:
val[(dst==2904).nonzero()]

tensor([[[0.5000, 0.5004, 0.4998]],

        [[0.5000, 0.4996, 0.5002]]], grad_fn=<IndexBackward0>)